one.addEventListener('click', function () {
    console.log("one works")
    document.getElementById('image').src = "images/1.png";
    document.getElementById('title').innerHTML = "Introduction";
    document.getElementById("text").innerHTML = "Horror is a subgenre of film that has been creeping into the mainstream for quite some time. Horror has, historically, come in waves. With some examples being the universal monsters era of the 30s and 40s with films such as <i>Frankenstein</i> (1931 and <i>Dracula</i> (1931), the slasher boom of the 70s to 80s which saw movies such as <i>Halloween</i> (1978) and <i>Friday the 13th</i> (1980). Personally I believe the most important eras to examine are the 2000s, 2010s, and 2020s. Throughout these three decades, horror has repeatedly been seen in the spotlight and the evolution of the genre is more prevalent than ever. This page aims to provide brief information and a short overlook through each decade, highlighting some key works along the way.";
});

two.addEventListener('click', function () {
    console.log("two works")
    document.getElementById('image').src = "images/2.png";
    document.getElementById('title').innerHTML = "2000s";
    document.getElementById("text").innerHTML = "The 2000s, in my opinion, are often overlooked when discussing the evolution and history of horror. This era saw a lot of horror films in the mainstream in many different veins. Many big name horror franchises were born, and held dominance in box offices for a fair amount of time. This era saw a boom in supernatural themed horror films. Following the success of <i>The Blair Witch Project</i> (1999), a boom of similar project in the “found footage” vein soon followed. Releases like the Spanish film <i>Rec</i> (2007), the sci-fi tinged <i>Cloverfield</i> (2008), and most notably, <i>Paranormal Activity</i> (2007) which saw incredible success with a meager budget. Another massive boom was seen in particularly violent films which harkened to older exploitation and arthouse films. These particular films from this era saw a heavy fixation on torture, gore, and violence as the main attraction. Most notably <i>Saw</i> (2004) but other titles such as <i>Hostel</i> (2005), <i>Martyrs</i> (2008), and Rob Zombies <i>House of 1000 Corpses</i> (2003) and <i>The Devils Rejects</i> (2005). Lastly, this era also saw a barrage of remakes and new sequels of many dormant series. Many view this as the beating of a dead horse, as these remakes and sequels usually didn’t offer a lot of new or particularly exciting elements other than the name attached. A lot of remakes released at the time were viewed simply as cash grabs. Some remakes would include <i>Thir13en Ghosts</i> (2001), <i>Prom Night</i> (2008), <i>The Last House on The Left</i> (2009), <i>Friday The 13th</i> (2009), <i>The Texas Chainsaw Massacre</i> (2003), <i>The Ring</i> (2001) and <i>The Wicker Man</i> (2006) to name a few. Some sequels include <i>Jason X</i> (2001), <i>Beyond Re-Animator</i> (2003), and <i>Exorcist: The Beginning (2004)</i>.";
});

three.addEventListener('click', function () {
    console.log("three works")
    document.getElementById('image').src = "images/3.png";
    document.getElementById('title').innerHTML = "2010s";
    document.getElementById("text").innerHTML = "The 2010s (my favourite time) was an interesting time for horror. There wasn’t a ton of definable subgenres or eras that emerged at this time as a lot of films continued trends from the 2000s. Shock horror like <i>Saw</i> and <i>Hostel</i> were followed by films like <i>Human Centipede</i> (2010) and <i>Tusk</i> (2014) while remakes and new sequels to old movies were still being cranked out like <i>Texas Chainsaw 3D</i> (2013), <i>Evil Dead</i> (2013), and a plethora of <i>Saw</i> sequel films. The most definable “era” was the heavy use of 3D in a lot of horror films at the time. Standout examples include, <i>Saw 3D</i> (2010) which was also called <i>Saw: The Final Chapter</i>, the aforementioned <i>Texas Chainsaw 3D</i>, <i>I Spit On Your Grave</i> (2010), and <i>Paranormal Activity: The Ghost Dimension</i> (2015) to name a few. Though the 2010s was a bit of mixed bag in terms of trends and definable eras, I believe this adds to the unique quality of the era I love. Particularly, a lot of very unique films were released closer to the end of this decade. While innovation has always been present within horror, a lot of visually interesting choices were seen in this era. From the surreal nightmarish imagery in films like <i>Annihilation (2018)</i>, and the thematically heavy identity centred imagery of works such as <i>Get Out</i> (2017). A lot of movies I particularly love and adore came from this era and I truly believe that this era boasts a turning point for horror that is widely overlooked. The works of Italian Canadian film maker Panos Cosmatos <i>Beyond The Black Rainbow</i> (2010) and <i>Mandy</i> (2018) are surreal stylized nightmares that boast an artistic and visually enthralling edge. <i>Sinister</i> (2012) boasts an amazing score/use of sound as well as many memorable and genuinely terrifying scenes, that turns up the usual horror tropes to eleven. <i>Train To Busan</i> (2016) expertly subverts the usual zombie film tropes and includes genuinely empathetic characters. The film is littered with well crafted devastating emotional beats throughout. Director Ari Aster’s two films <i>Hereditary</i> (2018) and <i>Midsommar</i> (2019) demonstrates incredible skill and range in building worlds within films. The former being a brightly lit vibrant cult nightmare, and the latter being a suffocating and tragic family drama with supernatural demonic undertones.";
});

four.addEventListener('click', function () {
    console.log("four works")
    document.getElementById('image').src = "images/4.png";
    document.getElementById('title').innerHTML = "2020s";
    document.getElementById("text").innerHTML = "With the onset of the 2020s, we’ve seen many notable films released within the horror subgenre. Uniquely, films made within this time span have seen a continued trend in subversion of the usual tropes whith some interesting concepts and ways of storytelling being implemented. As time goes on technology will continue to advance and new society wide fears will continue to develop. This fixation on fear that’s allowed horror to develop will allow it to evolve. We saw a great disruption in the film industry as a whole with the COVID pandemic, which extended to regular life. Life came to a genuine standstill but following the pandemic we saw tons of amazing films being released. I truly believe that horror will only continue to evolve, for better or for worse. Innovation naturally comes with good and bad, as has been seen with every major “era” of horror. Some notable films emerging from the 2020s are British film <i>Host</i> (2020) was shot, for the most part, directly on the videotelophony software Zoom, <i>Mad God</i> (2021) which introduced an entirely stop motion film to the modern horror audience. A couple others are <i>The Sadness</i> (2021) which fed an extremely violent East Asian edge to American audiences, and most recently <i>The Substance</i> (2024), which plays out as a body horror fuelled, depressing fever dream.";
});

const buttons = document.querySelectorAll('button');
buttons.forEach(button => {
  button.addEventListener('click', () => {
    buttons.forEach(btn => btn.classList.remove('active'));
    button.classList.add('active');
  });
});

